apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-deployment_2
  labels:
    app: k8-container-app_2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-container-app_2
  template:
    metadata:
      labels:
        app: k8-container-app_2
    spec:
      containers:
      - name: container_2
        image: gcr.io/csci5409-cloud/container_2:latest
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: container1_volume
            mountPath: /disha_PV_dir
      volumes:
        - name: container1
          persistentVolumeClaim:
            claimName: pvc-for-k8container-app