apiVersion: v1
kind: Service
metadata:
  name: container_2_service
spec:
  type: LoadBalancer
  selector:
    app: k8-container-app_2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000